name: ios_device_check
description: A Flutter plugin to use iOS DeviceCheck. Only supported on iOS 11.0 or newer.
version: 1.1.0
homepage: https://github.com/okadan/flutter_ios_device_check

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosDeviceCheckPlugin
