name: ios_device_check
description: A Flutter plugin to use iOS DeviceCheck. Only supported on iOS 11.0 or newer.
version: 1.2.0
homepage: https://github.com/okadan/flutter-ios-device-check

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosDeviceCheckPlugin
